spring:
  application:
    name: secondhand-backend
  datasource:
    url: "jdbc:postgresql://localhost:5432/secondhand_db"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: false

server:
  port: 8080

yayla:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    #jwtExpirationMs: 120000
    #jwtRefreshExpirationMs: 240000

aws:
  access:
    key: ***
  secret:
    key: ***
  s3:
    bucket: ***
    region: ***
    endpoint: ***