spring:
  application:
    name: secondhand-backend
  datasource:
    url: "jdbc:postgresql://localhost:5432/secondhand_db"
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        use_sql_comments: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.resend.com
    port: 587
    username: resend
    password: ${RESEND_MAIL_KEY}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true

server:
  port: 8080

secondhand:
  app:
    jwtSecret: ======================BezKoder=Spring===========================
    jwtExpirationMs: 3600000
    jwtRefreshExpirationMs: 86400000
    mailValidityHours: 10
    feUrl: http://localhost:8080
    mailFromAddress: noreply@swarmer.live
    #jwtExpirationMs: 120000
    #jwtRefreshExpirationMs: 240000

aws:
  access:
    key: ${AWS_ACCESS_KEY}
  secret:
    key: ${AWS_SECRET_KEY}
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    endpoint: ${AWS_S3_ENDPOINT}